// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: privacy/ota_coin.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OTACoin struct {
	Index           string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	OutputCoinIndex string `protobuf:"bytes,2,opt,name=output_coin_index,json=outputCoinIndex,proto3" json:"output_coin_index,omitempty"`
	Height          []byte `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *OTACoin) Reset()         { *m = OTACoin{} }
func (m *OTACoin) String() string { return proto.CompactTextString(m) }
func (*OTACoin) ProtoMessage()    {}
func (*OTACoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_60100f62d1b6a44d, []int{0}
}
func (m *OTACoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OTACoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OTACoin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OTACoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OTACoin.Merge(m, src)
}
func (m *OTACoin) XXX_Size() int {
	return m.Size()
}
func (m *OTACoin) XXX_DiscardUnknown() {
	xxx_messageInfo_OTACoin.DiscardUnknown(m)
}

var xxx_messageInfo_OTACoin proto.InternalMessageInfo

func (m *OTACoin) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *OTACoin) GetOutputCoinIndex() string {
	if m != nil {
		return m.OutputCoinIndex
	}
	return ""
}

func (m *OTACoin) GetHeight() []byte {
	if m != nil {
		return m.Height
	}
	return nil
}

func init() {
	proto.RegisterType((*OTACoin)(nil), "privacy.privacy.OTACoin")
}

func init() { proto.RegisterFile("privacy/ota_coin.proto", fileDescriptor_60100f62d1b6a44d) }

var fileDescriptor_60100f62d1b6a44d = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2c,
	0x4b, 0x4c, 0xae, 0xd4, 0xcf, 0x2f, 0x49, 0x8c, 0x4f, 0xce, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x87, 0x8a, 0xeb, 0x41, 0x69, 0xa5, 0x64, 0x2e, 0x76, 0xff, 0x10, 0x47,
	0xe7, 0xfc, 0xcc, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0xcc, 0xbc, 0x94, 0xd4, 0x0a, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x8b, 0x4b, 0x30, 0xbf, 0xb4, 0xa4, 0xa0, 0xb4, 0x04,
	0x6c, 0x4c, 0x3c, 0x44, 0x05, 0x13, 0x58, 0x05, 0x3f, 0x44, 0x02, 0xa4, 0xd9, 0x13, 0xac, 0x56,
	0x8c, 0x8b, 0x2d, 0x23, 0x35, 0x33, 0x3d, 0xa3, 0x44, 0x82, 0x59, 0x81, 0x51, 0x83, 0x27, 0x08,
	0xca, 0x73, 0x32, 0x3c, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18,
	0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x71, 0x98,
	0x3b, 0x2b, 0xf4, 0x61, 0xac, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0, 0x7b, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x7f, 0x8d, 0xcd, 0xc9, 0x00, 0x00, 0x00,
}

func (m *OTACoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OTACoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OTACoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Height) > 0 {
		i -= len(m.Height)
		copy(dAtA[i:], m.Height)
		i = encodeVarintOtaCoin(dAtA, i, uint64(len(m.Height)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OutputCoinIndex) > 0 {
		i -= len(m.OutputCoinIndex)
		copy(dAtA[i:], m.OutputCoinIndex)
		i = encodeVarintOtaCoin(dAtA, i, uint64(len(m.OutputCoinIndex)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintOtaCoin(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintOtaCoin(dAtA []byte, offset int, v uint64) int {
	offset -= sovOtaCoin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OTACoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovOtaCoin(uint64(l))
	}
	l = len(m.OutputCoinIndex)
	if l > 0 {
		n += 1 + l + sovOtaCoin(uint64(l))
	}
	l = len(m.Height)
	if l > 0 {
		n += 1 + l + sovOtaCoin(uint64(l))
	}
	return n
}

func sovOtaCoin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOtaCoin(x uint64) (n int) {
	return sovOtaCoin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OTACoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOtaCoin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OTACoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OTACoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOtaCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOtaCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOtaCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputCoinIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOtaCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOtaCoin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOtaCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputCoinIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOtaCoin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOtaCoin
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOtaCoin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Height = append(m.Height[:0], dAtA[iNdEx:postIndex]...)
			if m.Height == nil {
				m.Height = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOtaCoin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOtaCoin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOtaCoin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOtaCoin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOtaCoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOtaCoin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOtaCoin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOtaCoin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOtaCoin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOtaCoin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOtaCoin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOtaCoin = fmt.Errorf("proto: unexpected end of group")
)
